# Generated by Django 5.2.1 on 2025-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyinvestment',
            options={'ordering': ['-date'], 'verbose_name': 'Monthly Investment', 'verbose_name_plural': 'Monthly Investments'},
        ),
        migrations.AddField(
            model_name='monthlyinvestment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='monthly_contribution',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlyinvestment',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
