# Generated by Django 5.2.1 on 2025-05-26 06:29

from django.db import migrations

def set_current_prices(apps, schema_editor):
    MonthlyInvestment = apps.get_model('investments', 'MonthlyInvestment')
    for investment in MonthlyInvestment.objects.all():
        investment.current_price = investment.purchase_price
        investment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_remove_monthlyinvestment_investment_name'),
    ]

    operations = [
    ]
