# Generated by Django 5.2.1 on 2025-06-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_auto_20250526_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyinvestment',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
