# Generated by Django 5.2.1 on 2025-05-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_monthlyinvestment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyinvestment',
            name='investment_name',
        ),
    ]
